server:
  port: 8084

spring:
  application:
    name: notification-service
  output:
    ansi:
      enabled: always

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cryptex_notification}
    username: ${DB_USERNAME:cryptex}
    password: ${DB_PASSWORD:db@pass}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftlh
    charset: UTF-8
    check-template-location: true
    cache: false

notification:
  email:
    from: noreply@cryptex.com
    reply-to: support@cryptex.com

logging:
  level:
    org.springframework.security: DEBUG
