<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Email Verification</title>
</head>

<body>

<h2>Hello ${name}!</h2>

<p>
    Welcome to Cryptex.
</p>

<p>
    Please verify your email by clicking the button below.
</p>

<p>
    <a href="${verificationLink}">
        Verify Email
    </a>
</p>

<p>
    If you didn't create this account, simply ignore this email.
</p>

</body>
</html>