server:
  port: 8081

spring:
  application:
    name: auth-service
  output:
    ansi:
      enabled: always
  profiles:
    active: dev

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

    show-sql: true

    properties:
      hibernate:
        format_sql: true


jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION} # 15 minutes
  refresh-expiration: ${JWT_REFRESH_EXPIRATION} # 7 days
  verification-expiration: ${JWT_VERIFICATION_EXPIRATION} # 24 hours
  password-reset-expiration: ${JWT_PASSWORD_RESET_EXPIRATION} # 15 minutes


logging:
  level:
    org.springframework.security: DEBUG
